services:
  redis:
    image: redis:7-alpine
    volumes:
      - type: volume
        source: redis_data
        target: /data
        volume:
          nocopy: true
    command: ["redis-server", "--maxmemory", "20m", "--maxmemory-policy", "allkeys-lru", "--appendonly", "yes", "--databases", "2"]
    ports:
      - "6379:${REDIS_PORT:-6379}"

  s3mock:
    image: adobe/s3mock:latest
    volumes:
      - type: volume
        source: s3mock_data
        target: /data
        volume:
          nocopy: true
    ports:
      - "${S3_PORT:-24456}:9090"
    environment:
      COM_ADOBE_TESTING_S3MOCK_STORE_ROOT: /data
      COM_ADOBE_TESTING_S3MOCK_STORE_RETAIN_FILES_ON_EXIT: "true"
      COM_ADOBE_TESTING_S3MOCK_STORE_INITIAL_BUCKETS: settings
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:9090/favicon.ico"]
      interval: 5s
      timeout: 3s
      retries: 5

  mongodb:
    image: mongo:6.0.18
    volumes:
      - type: volume
        source: mongodb_data
        target: /data/db
        volume:
          nocopy: true
    ports:
      - "27017:${MONGODB_PORT:-27017}"

volumes:
  redis_data:
    driver: local
  s3mock_data:
    driver: local
  mongodb_data:
    driver: local
