services:
  redis:
    image: redis:7-alpine
    volumes:
      - type: volume
        source: redis_data
        target: /data
        volume:
          nocopy: true
    command: ["redis-server", "--maxmemory", "20m", "--maxmemory-policy", "allkeys-lru", "--appendonly", "yes", "--databases", "2"]
    ports:
      - "6379:${REDIS_PORT:-6379}"

  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    environment:
      MINIO_ROOT_USER: accesskey
      MINIO_ROOT_PASSWORD: secretkey
    volumes:
      - type: volume
        source: minio_data
        target: /data
        volume:
          nocopy: true
    ports:
      - "9000:${S3_PORT:-9000}"
      - "9001:${S3_CONSOLE_PORT:-9001}"  # Console access
    command: server /data --console-address ":9001"

  mongodb:
    image: mongo:6.0.18
    volumes:
      - type: volume
        source: mongodb_data
        target: /data/db
        volume:
          nocopy: true
    ports:
      - "27017:${MONGODB_PORT:-27017}"

volumes:
  redis_data:
    driver: local
  minio_data:
    driver: local
  mongodb_data:
    driver: local
