source "https://rubygems.org"

gemspec

# Exclude development-only gems from dependabot.
unless ENV["DEPENDABOT"]
  gem "rails"
  gem "rspec-rails", require: false
  gem "sqlite3", require: false
  gem "redis"
  gem "connection_pool"
  gem "aws-sdk-s3"
  gem "mongo"

  gem "puma"
  gem "rack"
  gem "rackup"

  gem "capybara"
  gem "cuprite"
  gem "webmock"
  gem "dotenv"

  gem "rake"
  gem "rspec", "~> 3.11"

  # Exclude development-only gems from the gemfiles generated by appraisal.
  unless defined?(::Appraisal::Gemfile) && is_a?(::Appraisal::Gemfile)
    gem "appraisal", require: false
    gem "standard", require: false
    gem "simplecov", require: false
    gem "yard", require: false
  end
end
