name: Continuous Integration
on:
  push:
    branches:
      - main
      - actions-*
  pull_request:
    branches-ignore:
      - actions-*
  workflow_dispatch:

env:
  TEST_REDIS_URL: default
  TEST_S3_URL: default
  TEST_MONGODB_URL: default
  FERRUM_PROCESS_TIMEOUT: "30"

jobs:
  specs:
    name: ruby-${{ matrix.ruby }} ${{ matrix.appraisal }}
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      minio:
        image: minio/minio:edge-cicd
        ports:
          - 9000:9000
        env:
          MINIO_ROOT_USER: accesskey
          MINIO_ROOT_PASSWORD: secretkey
        options: >-
          --health-cmd "curl -f http://localhost:9000/minio/health/live"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'db.runCommand("ping").ok' | mongosh --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "ruby"
            standardrb: true
            yard: true
          - ruby: "ruby"
            appraisal: "no_extensions"
          - ruby: "4.0"
            appraisal: "rails_8.1"
          - ruby: "3.3"
            appraisal: "rails_8.0"
          - ruby: "3.2"
            appraisal: "rails_7.2"
          - ruby: "3.2"
            appraisal: "rails_7.1"
          - ruby: "3.1"
            appraisal: "rails_7.0"
          - ruby: "3.0"
            appraisal: "rails_6.1"
          - ruby: "2.7"
            appraisal: "rails_6.0"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Ruby CI
        uses: bdurand/github-actions/ruby-ci@b7560883d5f8557f5d69fe8bd82721bbb5ed76df # v1.0.4
        with:
          ruby: ${{ matrix.ruby }}
          appraisal: ${{ matrix.appraisal }}
          bundler: ${{ matrix.bundler }}
          standardrb: ${{ matrix.standardrb }}
          yard: ${{ matrix.yard }}
          frozen_strings: ${{ matrix.frozen_strings }}
